### ISSUE TITLE
deliverTypeSystemByDescription fails on 6.0.6.1

### ISSUE THREAD

**Issue by glyncostello** [jazz-community/dng-type-system-management#2]
![Annotation 2019-09-09 171234](https://user-images.githubusercontent.com/55101593/64548264-33a24000-d326-11e9-9fc5-b31c794bc877.png)

See attached error message. Tool reports success but with an error. However the type system change is not propagated. 

The two streams are in different Project Areas but the streams have the correct source/target tags in the descriptions (the tool finds the correct streams). 

Some more info:
I created a PA and a stream in a component. Called this "Template". Populated it was a type system for the component (Artifacts types, attributes etc.). Then I created a new test prohect with a component and gave it the same type system (import component properties). I then made a change in the "Template" PA (created an artifact type called "lessons learned". But running the cmd-line tool does not propagate the change. 

I tried running the manual process of making a CSV file with source and target. This gave a slightly different error:

![Annotation 2019-09-09 174510](https://user-images.githubusercontent.com/55101593/64549905-a660ea80-d329-11e9-8429-01a5bccac98c.png)

**Comment by glyncostello** [comment]
Does the tool 'require' that each type system item has a defined RDF URI?

**Comment by glyncostello** [comment]
Ok, I went through and assigned every element in my source type system with a URI. I created a new component in a new PA and tried to run the tool again, but the same problem. Reports a success but no change to the attributes.

**Comment by glyncostello** [comment]
Ok, not sure what the difference between "import" and "Deliver" is, but "import" seems to be working as I expect.

**Comment by rsjazz** [comment]
No, there is no need for the URI with respect to the tool.
Import imports a type system from one stream for one component to one stream in another component.
Deliver, delivers the type system changes from one stream in one component to another stream in the same component.

**Comment by rsjazz** [comment]
> ![Annotation 2019-09-09 171234](https://user-images.githubusercontent.com/55101593/64548264-33a24000-d326-11e9-9fc5-b31c794bc877.png)
> 
> See attached error message. Tool reports success but with an error. However the type system change is not propagated.
> 
> The two streams are in different Project Areas but the streams have the correct source/target tags in the descriptions (the tool finds the correct streams).
> 
> Some more info:
> I created a PA and a stream in a component. Called this "Template". Populated it was a type system for the component (Artifacts types, attributes etc.). Then I created a new test prohect with a component and gave it the same type system (import component properties). I then made a change in the "Template" PA (created an artifact type called "lessons learned". But running the cmd-line tool does not propagate the change.
> 
> I tried running the manual process of making a CSV file with source and target. This gave a slightly different error:
> 
> ![Annotation 2019-09-09 174510](https://user-images.githubusercontent.com/55101593/64549905-a660ea80-d329-11e9-8429-01a5bccac98c.png)

You can not deliver the type system change across multiple components (and thus not across project areas). 

Maybe you try to figure out how import and delivery of type systems work manually, before trying to use automation?
