### ISSUE TITLE
Authentication issue 

### ISSUE THREAD

**Issue by oraafat** [jazz-community/dng-type-system-management#3]
1) I have dowloaded the requested files placed them in the same folder 
2) extracted tsm-1.2-20190327
3)
java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

4)error during my attempt to extract the data to CSV files as below 

java -jar tsm.jar -command exportConfigurations -url https://xxxxxxxxxxxxx:9443/rm -user xxxxxxx -password xxxxxx -project "ALM Data Model" -csvfile "../exporttest.csv" -csvDelimiter ";"

C:\Users\a-oraafat\Desktop\automation\tsm-1.2-20190327\TSM>java -jar tsm.jar -co
mmand exportConfigurations -url >server path< -use
r xxxxx -password xxxxxxx -project "ALM Data Model" -csvfile "../exportt
est.csv" -csvDelimiter ";"

TypeSystemManager Version: 1.2
[line: 41, col: 95] {W107} Bad URI: <https://jazzjts-qa.xxxxxxxx.net:9443/c
lmhelp> Code: 8/NON_INITIAL_DOT_SEGMENT in PATH: The path contains a segment /..
/ not at the beginning of a relative reference, or it contains a /./ These shoul
d be removed.
org.eclipse.lyo.client.exception.JazzAuthErrorException: OSLCC002: An error occu
rred attempting to login to the Jazz server.  Status code 404.  Server location:
 https://jazzrm-qa.xxxxxxxx:9443/rm.
        at org.eclipse.lyo.client.oslc.jazz.JazzFormAuthClient.login(JazzFormAut
hClient.java:199)
        at com.ibm.requirement.typemanagement.oslc.client.automation.commands.Ex
portConfigurationsCmd.execute(ExportConfigurationsCmd.java:143)
        at com.ibm.requirement.typemanagement.oslc.client.automation.framework.A
bstractCommand.run(AbstractCommand.java:79)
        at com.ibm.requirement.typemanagement.oslc.client.automation.DngTypeSyst
emManagement.execute(DngTypeSystemManagement.java:111)
        at com.ibm.requirement.typemanagement.oslc.client.automation.DngTypeSyst
emManagement.main(DngTypeSystemManagement.java:55)
OSLCC002: An error occurred attempting to login to the Jazz server.  Status code
 404.  Server location: https://jazzrm-qa.xxxxxxxx:9443/rm.
org.eclipse.lyo.client.exception.JazzAuthErrorException: OSLCC002: An error occu
rred attempting to login to the Jazz server.  Status code 404.  Server location:
 https://jazzrm-qa.xxxxxxxx:9443/rm.
        at org.eclipse.lyo.client.oslc.jazz.JazzFormAuthClient.login(JazzFormAut
hClient.java:199)
        at com.ibm.requirement.typemanagement.oslc.client.automation.commands.Ex
portConfigurationsCmd.execute(ExportConfigurationsCmd.java:143)
        at com.ibm.requirement.typemanagement.oslc.client.automation.framework.A
bstractCommand.run(AbstractCommand.java:79)
        at com.ibm.requirement.typemanagement.oslc.client.automation.DngTypeSyst
emManagement.execute(DngTypeSystemManagement.java:111)
        at com.ibm.requirement.typemanagement.oslc.client.automation.DngTypeSyst
emManagement.main(DngTypeSystemManagement.java:55)
Failed.

Could you please help what is missing in the previous steps and how exactly I should use either dng-type-system-management-1.2.tar.gz or dng-type-system-management-1.2.zip

**Comment by rsjazz** [comment]
1. Your Java Version is way too old. Use a current one.
2. Try to use an absolute path for the CSV file e.g. -csvfile "c:\Temp\exportDeliverTag_all.csv"
3. You can try to read the linked articles and set up a development environment - as stated, the code is a prototype and not production code.
4. The error complains about the path, try something like the example above.
5. Only the tsm*.zip file is runnable, the rest is basically code packaged by GIT.

**Comment by oraafat** [comment]
I have updated the java version and also added the full path for the CSV file , but I am still having the same error message as below 
 please note that I have a DNG environment up and running and I can reach it from the same machine I am trying to run tsm*.zip

C:\tsm-1.2-20190327\TSM>java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

C:\Users\a-oraafat\Desktop\automation\tsm-1.2-20190327\TSM>java -jar tsm.jar -co
mmand exportConfigurations -url https://xxxxxxxxx.net:9443/rm -use
r xxxxxx -password xxxxxx -project "ALM Data Model" -csvfile "C:\Users\a
-xxxxxt\Desktop\automation\exporttest.csv" -csvDelimiter ";"

TypeSystemManager Version: 1.2
[line: 41, col: 95] {W107} Bad URI: <https://jazzjts-qa.xxxxx:9443/c
lmhelp> Code: 8/NON_INITIAL_DOT_SEGMENT in PATH: The path contains a segment /..
/ not at the beginning of a relative reference, or it contains a /./ These shoul
d be removed.
org.eclipse.lyo.client.exception.JazzAuthErrorException: OSLCC002: An error occu
rred attempting to login to the Jazz server.  Status code 404.  Server location:
 https://jazzrm-qa.xxxx:9443/rm.
        at org.eclipse.lyo.client.oslc.jazz.JazzFormAuthClient.login(JazzFormAut
hClient.java:199)
        at com.ibm.requirement.typemanagement.oslc.client.automation.commands.Ex
portConfigurationsCmd.execute(ExportConfigurationsCmd.java:143)
        at com.ibm.requirement.typemanagement.oslc.client.automation.framework.A
bstractCommand.run(AbstractCommand.java:79)
        at com.ibm.requirement.typemanagement.oslc.client.automation.DngTypeSyst
emManagement.execute(DngTypeSystemManagement.java:111)
        at com.ibm.requirement.typemanagement.oslc.client.automation.DngTypeSyst
emManagement.main(DngTypeSystemManagement.java:55)
OSLCC002: An error occurred attempting to login to the Jazz server.  Status code
 404.  Server location: https://jazzrm-qa.xxxxxxxx.net:9443/rm.
org.eclipse.lyo.client.exception.JazzAuthErrorException: OSLCC002: An error occu
rred attempting to login to the Jazz server.  Status code 404.  Server location:
 https://jazzrm-qa.xxxxxxr.net:9443/rm.
        at org.eclipse.lyo.client.oslc.jazz.JazzFormAuthClient.login(JazzFormAut
hClient.java:199)
        at com.ibm.requirement.typemanagement.oslc.client.automation.commands.Ex
portConfigurationsCmd.execute(ExportConfigurationsCmd.java:143)
        at com.ibm.requirement.typemanagement.oslc.client.automation.framework.A
bstractCommand.run(AbstractCommand.java:79)
        at com.ibm.requirement.typemanagement.oslc.client.automation.DngTypeSyst
emManagement.execute(DngTypeSystemManagement.java:111)
        at com.ibm.requirement.typemanagement.oslc.client.automation.DngTypeSyst
emManagement.main(DngTypeSystemManagement.java:55)
Failed.

**Comment by rsjazz** [comment]
I have the same issue and I don't know why and where. I know that the project area I am working against is not enabled for global configuration management.

If I can find some time to look into it, I will.

**Comment by rsjazz** [comment]
The issue happens in the LYO client. I don't know why. Thsi is going to be hard to find.

**Comment by rsjazz** [comment]
When you login to the JTS, the server responds with HTML (as if the login did not happen). There is no class registered that is able to serialiize or deserialize HTML. That causes the error. I am not sure how to fix that.

**Comment by rsjazz** [comment]
At the moment it looks like the first error is not problematic, provided you have given the correct username, password and project area name. The second error must be due to an incorrect username or password. The login process works for me.
